require(readxl)
require(plotly)
require(dygraphs)
require(png)
require("DT")
###### UI Function ######



DomesticRHIOutput <- function(id) {
  ns <- NS(id)
  tagList(
    tabsetPanel(
      tabPanel("Accredited installations time series",
               fluidRow(column(8,
                               h3("Domestic RHI - accredited installations", style = "color: #39ab2c;  font-weight:bold"),
                               h4(textOutput(ns('DomRHIInstallationsOutputSubtitle')), style = "color: #39ab2c;")
               ),
               column(
                 4, style = 'padding:15px;',
                 downloadButton(ns('DomRHIInstallationsOutput.png'), 'Download Graph', style="float:right")
               )),
               
               tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;"),
               #dygraphOutput(ns("DomesticRHIPlot")),
               plotlyOutput(ns("DomRHIInstallationsOutputPlot"))%>% withSpinner(color="#39ab2c"),
               tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;")),
      tabPanel("Heat generated",
    fluidRow(column(8,
                    h3("Domestic RHI - heat generated by technology", style = "color: #39ab2c;  font-weight:bold"),
                    h4(textOutput(ns('DomesticRHISubtitle')), style = "color: #39ab2c;")
    ),
             column(
               4, style = 'padding:15px;',
               downloadButton(ns('DomesticRHI.png'), 'Download Graph', style="float:right")
             )),
    
    tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;"),
    #dygraphOutput(ns("DomesticRHIPlot")),
    plotlyOutput(ns("DomesticRHIPlot"))%>% withSpinner(color="#39ab2c"),
    tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;")),
    tabPanel("On/Off-Grid",
             fluidRow(column(8,
                             h3("Proportion of full accreditations which are on-grid and off-grid", style = "color: #39ab2c;  font-weight:bold"),
                             h4(textOutput(ns('DomRHIUrbanRuralSubtitle')), style = "color: #39ab2c;")
             ),
             column(
               4, style = 'padding:15px;',
               downloadButton(ns('DomRHIUrbanRural.png'), 'Download Graph', style="float:right")
             )),
             
             tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;"),
             #dygraphOutput(ns("DomesticRHIPlot")),
             plotlyOutput(ns("DomRHIUrbanRuralPlot"))%>% withSpinner(color="#39ab2c"),
             tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;"))

    ),
    fluidRow(
    column(10,h3("Commentary", style = "color: #39ab2c;  font-weight:bold")),
    column(2,style = "padding:15px",actionButton(ns("ToggleText"), "Show/Hide Text", style = "float:right; "))),
    
    fluidRow(
    uiOutput(ns("Text"))
    ),
    tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;"),
    tabsetPanel(
      tabPanel("Cumulative Installations",
               fluidRow(
                 column(10, h3("Data - Cumulative number of domestic RHI accredited applications", style = "color: #39ab2c;  font-weight:bold")),
                 column(2, style = "padding:15px",  actionButton(ns("ToggleTable2"), "Show/Hide Table", style = "float:right; "))
               ),
               fluidRow(
                 column(12, dataTableOutput(ns("CumulativeInstallationsOutputTable"))%>% withSpinner(color="#39ab2c"))),
               tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;")),
      tabPanel("Local Authority Installations",
               fluidRow(
                 uiOutput(ns("SubtitleYearText")),
                 column(2, style = "padding:15px",  actionButton(ns("ToggleTable3"), "Show/Hide Table", style = "float:right; "))
               ),
               fluidRow(
                 column(12, dataTableOutput(ns("DomRHIInstallationsOutputTable"))%>% withSpinner(color="#39ab2c"))),
               tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;")),
      tabPanel("Installations by region",
               fluidRow(
                 column(10, h3("Data - Number of domestic RHI accredited applications by region, Scotland, July 2021", style = "color: #39ab2c;  font-weight:bold")),
                 column(2, style = "padding:15px",  actionButton(ns("ToggleTable5"), "Show/Hide Table", style = "float:right; "))
               ),
               fluidRow(
                 column(12, dataTableOutput(ns("DomesticRHIRegionTable"))%>% withSpinner(color="#39ab2c"))),
               tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;")),
      tabPanel("Heat generated",
    fluidRow(
    column(10, h3("Data - Domestic RHI - heat generated by technology, April 2014 - June 2021", style = "color: #39ab2c;  font-weight:bold")),
    column(2, style = "padding:15px",  actionButton(ns("ToggleTable1"), "Show/Hide Table", style = "float:right; "))
    ),
    fluidRow(
      column(12, dataTableOutput(ns("DomesticRHITable"))%>% withSpinner(color="#39ab2c"))),
    tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;")),
    tabPanel("Urban/Rural and On/Off grid",
             fluidRow(
               uiOutput(ns("SubtitleYearText2")),
               column(2, style = "padding:15px",  actionButton(ns("ToggleTable4"), "Show/Hide Table", style = "float:right; "))
             ),
             fluidRow(
               column(12, dataTableOutput(ns("DomRHIUrbanRuralTable"))%>% withSpinner(color="#39ab2c"))),
             tags$hr(style = "height:3px;border:none;color:#39ab2c;background-color:#39ab2c;"))

    ),
    fluidRow(
      column(2, HTML("<p><strong>Last Updated:</strong></p>")),
      column(2,
             UpdatedLookup(c("BEISRHI","OGFGEMdrhi"))),
      column(1, align = "right",
             HTML("<p><strong>Reason:</strong></p>")),
      column(7, align = "right", 
             p("Regular updates")
      )),
    fluidRow(p(" ")),
    fluidRow(
      column(2, HTML("<p><strong>Update Expected:</strong></p>")),
      column(2,
             DateLookup(c("BEISRHI","OGFGEMdrhi"))),
      column(1, align = "right",
             HTML("<p><strong>Sources:</strong></p>")),
      column(7, align = "right",
        SourceLookup("BEISRHI"),
        SourceLookup("OGFGEMdrhi")
        
      )
    )
  )
}




###### Server ######
DomesticRHI <- function(input, output, session) {
  
  
  if (exists("PackageHeader") == 0) {
    source("Structure/PackageHeader.R")
  }
  
  print("DomesticRHI.R")

  
  output$DomesticRHISubtitle <- renderText({
    
    paste("Scotland, Apr 2014 - June 2021")
  })
  
  output$DomesticRHIPlot <- renderPlotly  ({
    
    Data <-
      read_excel(
        "Structure/CurrentWorking.xlsx",
        sheet = "Domestic RHI", 
        skip = 14, n_max = 5)
    
    Data <- Data[1:4,c(1,2)]
    
    names(Data) <- c("Tech", "Heat generated")
    
    Data$TechLabel <- Data$Tech
    
    Data$Tech <- paste0("<b>",Data$Tech,"</b>")
    
    Data$Tech <- str_wrap(Data$Tech, 16)
    
    ChartColours <- c("#39ab2c", "#FF8500", "#FFFFFF")
    LineColours <- c("#fc4e2a","#feb24c","#fed976","#addd8e","#41ab5d")
    
    p <-  plot_ly(Data, 
                  y = ~Tech, 
                  x = ~ `Heat generated`, 
                  type = 'bar', 
                  name = 'Heat generated',
                  hoverinfo = "text",
                  text = paste0("Heat generated: ", round(Data$`Heat generated`, 0), " GWh"),
                  orientation = 'h',
                  marker = list(color = "#31a354")
                  )%>%

      layout(
        barmode = 'group',
        bargap = 0.25,
        legend = list(font = list(color = "#39ab2c"),
                      orientation = 'h'),
        hoverlabel = list(font = list(color = "white"),
                          hovername = 'text'),
        hovername = 'text',
        xaxis = list(title = "",
                     zeroline = FALSE,
                     tickformat = "",
                     showgrid = TRUE,
                     range = c(-0.01, max(Data$`Heat generated`)+0.1),
                     x = 0.5
                     
                     ),
        yaxis = list(
          title = "",
          tickformat = "",
          autorange = "reversed",
          showgrid = FALSE,
          zeroline = FALSE,
          rangemode = "tozero"
        )
      ) %>% 
      config(displayModeBar = F)
    p
    
    
    
  })
  
  SubtitleYear <-
    read_excel(
      "Structure/CurrentWorking.xlsx",
      sheet = "Domestic RHI", col_names = FALSE, 
      skip = 61)
  SubtitleYear <- SubtitleYear[complete.cases(SubtitleYear),]
  
  names(SubtitleYear)[1] <- "Year"
  
  output$SubtitleYearText <- renderUI({
    column(10, h3(paste("Data - Number of accredited installations by Local Authority -", format(max(SubtitleYear$Year), "%b %Y")) , style = "color: #39ab2c;  font-weight:bold"))
    
  })
  
  output$SubtitleYearText2 <- renderUI({
    column(10, h3(paste("Number of full accreditations on/off the gas grid by aggregated rural/urban classification, Domestic -", "April 2014 to December 2020") , style = "color: #39ab2c;  font-weight:bold"))
    
  })
  
  output$DomRHIInstallationsOutputSubtitle <- renderText({
    
    paste("Scotland,", format(min(SubtitleYear$Year), "%b %Y"),"-", format(max(SubtitleYear$Year), "%b %Y"))
  })
  
  output$DomRHIInstallationsOutputPlot <- renderPlotly  ({
    
    Data <-
      read_excel(
        "Structure/CurrentWorking.xlsx",
        sheet = "Domestic RHI", col_names = FALSE, 
        skip = 61)
    Data <- Data[complete.cases(Data),][c(1,3,5,7,9,11)]
    
    names(Data) <- c("Year", "Air Source", "Ground Source", "Biomass", "Solar Thermal", "Total")
    
    Data[2:ncol(Data)] %<>% lapply(function(x) as.numeric(as.character(x)))
    
    DomRHIInstallationsOutputTech <- Data[order(Data$Year),]
    
    ChartColours <- c("#39ab2c", "#FF8500", "#FFFFFF")
    LineColours <- c("#39ab2c", "#ef3b2c","#fc9272","#fb6a4a","#fcbaa0")
    
    p <-  plot_ly(DomRHIInstallationsOutputTech, x = ~ Year ) %>%  
      add_trace(y = ~ `Total`,
                name = "Total",
                type = 'scatter',
                mode = 'lines',
                legendgroup = "1",
                text = paste0(
                  "Total: ",
                  format(round(DomRHIInstallationsOutputTech$`Total`, digits = 0), big.mark = ","),
                  "\nYear: ",
                  format(DomRHIInstallationsOutputTech$Year, "%b %Y")
                ),
                hoverinfo = 'text',
                line = list(width = 6, color = LineColours[1], dash = "none")
      ) %>% 
      add_trace(y = ~ `Air Source`,
                name = "Air Source",
                type = 'scatter',
                mode = 'lines',
                legendgroup = "2",
                text = paste0(
                  "Air Source: ",
                  format(round(DomRHIInstallationsOutputTech$`Air Source`, digits = 0), big.mark = ","),
                  "\nYear: ",
                  format(DomRHIInstallationsOutputTech$Year, "%b %Y")
                ),
                hoverinfo = 'text',
                line = list(width = 6, color = LineColours[2], dash = "none")
      ) %>% 
      add_trace(y = ~ `Ground Source`,
                name = "Ground Source",
                type = 'scatter',
                mode = 'lines',
                legendgroup = "3",
                text = paste0(
                  "Ground Source: ",
                  format(round(DomRHIInstallationsOutputTech$`Ground Source`, digits = 0), big.mark = ","),
                  "\nYear: ",
                  format(DomRHIInstallationsOutputTech$Year, "%b %Y")
                ),
                hoverinfo = 'text',
                line = list(width = 6, color = LineColours[4], dash = "none")
      ) %>% 
      add_trace(y = ~ `Biomass`,
                name = "Biomass",
                type = 'scatter',
                mode = 'lines',
                legendgroup = "4",
                text = paste0(
                  "Biomass: ",
                  format(round(DomRHIInstallationsOutputTech$`Biomass`, digits = 0), big.mark = ","),
                  "\nYear: ",
                  format(DomRHIInstallationsOutputTech$Year, "%b %Y")
                ),
                hoverinfo = 'text',
                line = list(width = 6, color = LineColours[3], dash = "none")
      ) %>% 
      add_trace(y = ~ `Solar Thermal`,
                name = "Solar Thermal",
                type = 'scatter',
                mode = 'lines',
                legendgroup = "5",
                text = paste0(
                  "Solar Thermal: ",
                  format(round(DomRHIInstallationsOutputTech$`Solar Thermal`, digits = 0), big.mark = ","),
                  "\nYear: ",
                  format(DomRHIInstallationsOutputTech$Year, "%b %Y")
                ),
                hoverinfo = 'text',
                line = list(width = 6, color = LineColours[5], dash = "none")
      ) %>% 
      add_trace(
        data = tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Total` != 0),], 1),
        x = ~ Year,
        y = ~ `Total`,
        name = "Total",
        legendgroup = "1",
        text = paste0(
          "Total: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Total` != 0),], 1)$`Total`, big.mark = ","),
          "\nYear: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Total` != 0),], 1)$Year, "%b %Y")
        ),
        hoverinfo = 'text',
        showlegend = FALSE ,
        type = "scatter",
        mode = 'markers',
        marker = list(size = 18, 
                      color = LineColours[1])
      ) %>%
      add_trace(
        data = tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Air Source` != 0),], 1),
        x = ~ Year,
        y = ~ `Air Source`,
        name = "Air Source",
        legendgroup = "2",
        text = paste0(
          "Air Source: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Air Source` != 0),], 1)$`Air Source`, big.mark = ","),
          "\nYear: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Air Source` != 0),], 1)$Year, "%b %Y")
        ),
        hoverinfo = 'text',
        showlegend = FALSE ,
        type = "scatter",
        mode = 'markers',
        marker = list(size = 18, 
                      color = LineColours[2])
      ) %>% 
      add_trace(
        data = tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Ground Source` != 0),], 1),
        x = ~ Year,
        y = ~ `Ground Source`,
        name = "Ground Source",
        legendgroup = "3",
        text = paste0(
          "Ground Source: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Ground Source` != 0),], 1)$`Ground Source`, big.mark = ","),
          "\nYear: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Ground Source` != 0),], 1)$Year, "%b %Y")
        ),
        hoverinfo = 'text',
        showlegend = FALSE ,
        type = "scatter",
        mode = 'markers',
        marker = list(size = 18, 
                      color = LineColours[4])
      ) %>% 
      add_trace(
        data = tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Biomass` != 0),], 1),
        x = ~ Year,
        y = ~ `Biomass`,
        name = "Biomass",
        legendgroup = "4",
        text = paste0(
          "Biomass: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Biomass` != 0),], 1)$`Biomass`, big.mark = ","),
          "\nYear: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Biomass` != 0),], 1)$Year, "%b %Y")
        ),
        hoverinfo = 'text',
        showlegend = FALSE ,
        type = "scatter",
        mode = 'markers',
        marker = list(size = 18, 
                      color = LineColours[3])
      ) %>% 
      add_trace(
        data = tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Solar Thermal` != 0),], 1),
        x = ~ Year,
        y = ~ `Solar Thermal`,
        name = "Solar Thermal",
        legendgroup = "5",
        text = paste0(
          "Solar Thermal: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Solar Thermal` != 0),], 1)$`Solar Thermal`, big.mark = ","),
          "\nYear: ",
          format(tail(DomRHIInstallationsOutputTech[which(DomRHIInstallationsOutputTech$`Solar Thermal` != 0),], 1)$Year, "%b %Y")
        ),
        hoverinfo = 'text',
        showlegend = FALSE ,
        type = "scatter",
        mode = 'markers',
        marker = list(size = 18, 
                      color = LineColours[5])
      ) %>% 
      layout(
        barmode = 'stack',
        bargap = 0.66,
        legend = list(font = list(color = "#39ab2c"),
                      orientation = 'h'),
        hoverlabel = list(font = list(color = "white"),
                          hovername = 'text'),
        hovername = 'text',
        xaxis = list(title = "",
                     showgrid = FALSE),
        yaxis = list(
          title = "",
          showgrid = TRUE,
          zeroline = TRUE,
          zerolinecolor = ChartColours[1],
          zerolinewidth = 2,
          rangemode = "tozero"
        )
      ) %>% 
      config(displayModeBar = F)
    p
    
    
    
  })
  
  output$DomesticRHITable = renderDataTable({
    
    Data <-
      read_excel(
        "Structure/CurrentWorking.xlsx",
        sheet = "Domestic RHI", 
        skip = 14, n_max = 5)
    
    names(Data) <- c("Technology", "Heat paid for under the domestic scheme - GWh", "Heat paid for under the domestic scheme - %", "Number of installations receiving payment - MWh", "Number of installations receiving payment - %", "Estimated capacity of Accredited Applications (MW)", "% of total")
    
    DomesticRHI <- Data
    
    datatable(
      DomesticRHI[c(1,2,3,6)],
      extensions = 'Buttons',
      
      rownames = FALSE,
      options = list(
        paging = TRUE,
        pageLength = -1,
        searching = TRUE,
        fixedColumns = FALSE,
        autoWidth = TRUE,
        title = "Domestic RHI heat generated and capacity by technology, Scotland, April 2014 - June 2021",
        dom = 'ltBp',
        buttons = list(
          list(extend = 'copy'),
          list(
            extend = 'excel',
            title = "Domestic RHI heat generated and capacity by technology, Scotland, April 2014 - June 2021",
            header = TRUE
          ),
          list(extend = 'csv',
               title = "Domestic RHI heat generated and capacity by technology, Scotland, April 2014 - June 2021")
        ),
        
        # customize the length menu
        lengthMenu = list( c(10, 20, -1) # declare values
                           , c(10, 20, "All") # declare titles
        ), # end of lengthMenu customization
        pageLength = 10
      )
    ) %>%
      formatRound(c(2:4), 0) %>% 
      formatPercentage(c(3), 1)
  })
  
  output$DomesticRHIRegionTable = renderDataTable({
    
    OFGEMRHIDom <- read_delim("Processed Data/Output/RHI/OFGEMRHIDom.txt", 
                              "\t", escape_double = FALSE, trim_ws = TRUE)
    
    datatable(
      OFGEMRHIDom,
      extensions = 'Buttons',
      
      rownames = FALSE,
      options = list(
        paging = TRUE,
        pageLength = -1,
        searching = TRUE,
        fixedColumns = FALSE,
        autoWidth = TRUE,
        title = "Number of domestic RHI accredited applications by region, Scotland, July 2020",
        dom = 'ltBp',
        buttons = list(
          list(extend = 'copy'),
          list(
            extend = 'excel',
            title = "Number of domestic RHI accredited applications by region, Scotland, July 2020",
            header = TRUE
          ),
          list(extend = 'csv',
               title = "Number of domestic RHI accredited applications by region, Scotland, July 2020")
        ),
        
        # customize the length menu
        lengthMenu = list( c(10, 20, -1) # declare values
                           , c(10, 20, "All") # declare titles
        ), # end of lengthMenu customization
        pageLength = 10
      )
    ) %>%
      formatRound(c(2:6), 0) 
  })
  
  output$CumulativeInstallationsOutputTable = renderDataTable({
    
    Data <-
      read_excel(
        "Structure/CurrentWorking.xlsx",
        sheet = "Domestic RHI", 
        skip = 60)
    
    names(Data) <- c("Date", "Air Source - Applications", "Air Source",
                    "Ground Source - Applications", "Ground Source",
                     "Biomass - Applications", "Biomass",
                     "Solar Thermal - Applications", "Solar Thermal",
                     "Total - Applications", "Total")
    
    Data$Date <- format(Data$Date, "%b %Y")

    datatable(
      Data[c(1,3,5,7,9,11)],
      extensions = 'Buttons',
      
      rownames = FALSE,
      options = list(
        paging = TRUE,
        pageLength = -1,
        searching = TRUE,
        fixedColumns = FALSE,
        autoWidth = TRUE,
        title = "Cumulative number of domestic RHI accredited applications, Scotland",
        dom = 'ltBp',
        buttons = list(
          list(extend = 'copy'),
          list(
            extend = 'excel',
            title = "Cumulative number of domestic RHI accredited applications, Scotland",
            header = TRUE
          ),
          list(extend = 'csv',
               title = "Cumulative number of domestic RHI accredited applications, Scotland")
        ),
        
        # customize the length menu
        lengthMenu = list( c(10, 20, -1) # declare values
                           , c(10, 20, "All") # declare titles
        ), # end of lengthMenu customization
        pageLength = 10
      )
    ) %>%
      formatRound(c(2:6), 0)
  })
  
  output$DomRHIInstallationsOutputTable = renderDataTable({
    
    Data <-
      read_excel(
        "Structure/CurrentWorking.xlsx",
        sheet = "Domestic RHI", col_names = T, 
        skip = 23, n_max = 34)
    
names(Data)[1] <- "LA Code"
    
    DomRHIInstallationsOutputTech <- Data[c(2,1,3)]
    
    datatable(
      DomRHIInstallationsOutputTech,
      extensions = 'Buttons',
      
      rownames = FALSE,
      options = list(
        paging = TRUE,
        pageLength = -1,
        searching = TRUE,
        fixedColumns = FALSE,
        autoWidth = TRUE,
        title = paste("Number of accredited installations by Local Authority -", format(max(SubtitleYear$Year), "%b %Y")),
        dom = 'ltBp',
        buttons = list(
          list(extend = 'copy'),
          list(
            extend = 'excel',
            title = paste("Number of accredited installations by Local Authority -", format(max(SubtitleYear$Year), "%b %Y")),
            header = TRUE
          ),
          list(extend = 'csv',
               title = paste("Number of accredited installations by Local Authority -", format(max(SubtitleYear$Year), "%b %Y")))
        ),
        
        # customize the length menu
        lengthMenu = list( c(10, 20, -1) # declare values
                           , c(10, 20, "All") # declare titles
        ), # end of lengthMenu customization
        pageLength = 10
      )
    ) %>%
      formatRound(c(3), 0)
  })
  
  output$DomRHIUrbanRuralTable = renderDataTable({
    
    DomUrbanRural <- read_delim("Processed Data/Output/RHI/DomUrbanRural.txt", 
                                "\t", escape_double = FALSE, trim_ws = TRUE)
    
    datatable(
      DomUrbanRural,
      extensions = 'Buttons',
      
      rownames = FALSE,
      options = list(
        paging = TRUE,
        pageLength = -1,
        searching = TRUE,
        fixedColumns = FALSE,
        autoWidth = TRUE,
        title = paste("Number of full accreditations on/off the gas grid by aggregated rural/urban classification, Domestic", "November 2011 to December 2020"),
        dom = 'ltBp',
        buttons = list(
          list(extend = 'copy'),
          list(
            extend = 'excel',
            title = paste("Number of full accreditations on/off the gas grid by aggregated rural/urban classification, Domestic", "November 2011 to December 2020"),
            header = TRUE
          ),
          list(extend = 'csv',
               title = paste("Number of full accreditations on/off the gas grid by aggregated rural/urban classification, Domestic", "November 2011 to December 2020"))
        ),
        
        # customize the length menu
        lengthMenu = list( c(10, 20, -1) # declare values
                           , c(10, 20, "All") # declare titles
        ), # end of lengthMenu customization
        pageLength = 10
      )
    ) %>%
      formatRound(c(2:10), 0) %>% 
      formatStyle(c(6:9), fontStyle = "italic") %>% 
      formatStyle(10, fontWeight = "bold")
  })
  
  output$Text <- renderUI({
    tagList(column(12,
                   HTML(
                     paste(readtext("Structure/2 - Renewables/Heat/DomesticRHI.txt")[2])
                     
                   )))
  })
  
 observeEvent(input$ToggleTable1, {
    toggle("DomesticRHITable")
  })
  
  observeEvent(input$ToggleTable2, {
    toggle("CumulativeInstallationsOutputTable")
  })
  
  observeEvent(input$ToggleTable3, {
    toggle("DomRHIInstallationsOutputTable")
  })
  
  observeEvent(input$ToggleTable4, {
    toggle("DomRHIUrbanRuralTable")
  })
  
  observeEvent(input$ToggleTable5, {
    toggle("DomesticRHIRegionTable")
  })
  

  
  observeEvent(input$ToggleText, {
    toggle("Text")
  })
  
  
  output$DomesticRHI.png <- downloadHandler(
    filename = "DomesticRHI.png",
    content = function(file) {

      Data <-
        read_excel(
          "Structure/CurrentWorking.xlsx",
          sheet = "Domestic RHI", col_names = FALSE, 
          skip = 15, n_max = 4)
      
      Data <- Data[c(1,2)]
      
      Data <- as.data.frame(Data)
      
      names(Data) <- c("Tech", "Heat generated")
      
      DomesticRHI <- Data
      
      DomesticRHI <- arrange(DomesticRHI, -row_number())
      
      DomesticRHI$Tech <-
        factor(DomesticRHI$Tech,
               levels = unique(DomesticRHI$Tech),
               ordered = TRUE)
      
      DomesticRHI <- melt(DomesticRHI, id.vars = "Tech")
      
      
      DomesticRHI$variable <-
        factor(
          DomesticRHI$variable,
          levels = unique(DomesticRHI$variable),
          ordered = TRUE
        )
      
      DomesticRHI <- DomesticRHI %>%
        group_by(Tech) %>%
        mutate(pos = cumsum(value) - value / 2) %>%
        mutate(top = sum(value))
      
      plottitle <-
        "Domestic RHI - heat generated by technology"
      sourcecaption <- "Source: BEIS"
      
      ChartColours <- c("#39ab2c", "#FF8500")
      BarColours <-
        c(
          "#31a354",
          "#addd8e"
        )
      
      
      DomesticRHIChart <- DomesticRHI %>%
        ggplot(aes(x = Tech, y = value, fill = variable), family = "Century Gothic") +
        scale_fill_manual(
          "variable",
          values = c(
            "Heat generated" = BarColours[1]
          )
        ) +
        geom_bar(position = "dodge",
                 stat = "identity",
                 width = .8) +
        geom_text(position = position_dodge(width = .8),
                  aes(
                    y = value + max(DomesticRHI$value)*0.02,
                    fill = variable,
                    label = paste(round(value, 0), "GWh"),
                    hjust = 0
                  ),
                  fontface = 2,
                  colour =  ChartColours[1],
                  family = "Century Gothic") +
        
        annotate(
          "text",
          x = DomesticRHI$Tech,
          y = -(max(DomesticRHI$value)*0.15),
          label = ifelse(DomesticRHI$Tech == "z", "", str_wrap(DomesticRHI$Tech, width = 13)),
          family = "Century Gothic",
          fontface = 2,
          colour =  ChartColours[1]
        )
      
      DomesticRHIChart
      
      
      DomesticRHIChart <-
        StackedBars(DomesticRHIChart,
                    DomesticRHI,
                    plottitle,
                    sourcecaption,
                    ChartColours)
      
      DomesticRHIChart <-
        DomesticRHIChart +
        labs(subtitle = "Scotland, Apr 2014 - June 2021") +
        ylim(
          -(max(DomesticRHI$value)*0.22),
          max(DomesticRHI$value)*1.12
        ) +
        coord_flip()
      
      DomesticRHIChart
      
      ggsave(
        file,
        plot = DomesticRHIChart,
        width = 17.5,
        height = 12,
        units = "cm",
        dpi = 300
      )
    }
  )



output$DomRHIInstallationsOutput.png <- downloadHandler(
  filename = "DomRHIInstallationsOutput.png",
  content = function(file) {
    
    RHIDom <-
      read_excel(
        "Structure/CurrentWorking.xlsx",
        sheet = "Domestic RHI", skip = 60)
    
    RHIDom[c(2,4,6,8,10)] <- RHIDom[c(3,5,7,9,11)]
    
    RHIDom <- RHIDom[c(1,2,4,6,8,10)]
  
    names(RHIDom) <- c( "Year", "Air Source heat pump", "Ground Source heat pump", "Biomass", "Solar Thermal", "Total")
    
    RHIDom$Year <- ymd(RHIDom$Year)
    
    RHIDom[2:6] %<>% lapply(function(x) as.numeric(as.character(x)))
    RHIDom <- as.data.frame(RHIDom)
    
    RHIDom <- RHIDom[order(RHIDom$Year),]
    
    ### variables
    ChartColours <- c("#39ab2c", "#FF8500", "#FFFFFF")
    LineColours <- c("#39ab2c", "#ef3b2c","#fc9272","#fb6a4a","#fcbaa0")
    sourcecaption = "Source: BEIS"
    plottitle = "Domestic RHI - Accredited Installations"
    
    #RHIDom$OilPercentage <- PercentLabel(RHIDom$Oil)
    
    RHIWidth <- max(RHIDom$Year) - min(RHIDom$Year)
    
    RHIDomChart <- RHIDom %>%
      ggplot(aes(x = Year), family = "Century Gothic") +
      geom_line(
        aes(
          y = `Air Source heat pump`,
          label = percent(`Air Source heat pump`)
        ),
        colour = LineColours[2],
        size = 1.5,
        family = "Century Gothic"
      )+ 
      geom_text(
        aes(
          x = Year - (RHIWidth*0.07),
          y = `Air Source heat pump`,
          label = ifelse(Year == min(Year), format(`Air Source heat pump`, big.mark = ","), ""),
          hjust = 0.5,
          vjust = 1,
          fontface = 2
        ),colour = LineColours[2],
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = Year + (RHIWidth*0.07),
          y = `Air Source heat pump`,
          label = ifelse(Year == max(Year), format(`Air Source heat pump`, big.mark = ","), ""),
          hjust = 0.5,
          fontface = 2
        ),colour = LineColours[2],
        family = "Century Gothic"
      ) +
      geom_point(
        data = tail(RHIDom, 1),
        aes(
          x = Year,
          y = `Air Source heat pump`,
          show_guide = FALSE
        ),colour = LineColours[2],
        size = 4,
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = mean(Year)-3,
          y = mean(`Air Source heat pump`,),
          label = "Air Source heat pump",
          hjust = 0.5,
          vjust = -2.5,
          
          fontface = 2
        ),colour = LineColours[2],
        family = "Century Gothic"
      ) +
      geom_line(
        aes(
          y = `Ground Source heat pump`,
          label = percent(`Ground Source heat pump`)
        ),
        colour = LineColours[4],
        size = 1.5,
        family = "Century Gothic"
      )+ 
      geom_text(
        aes(
          x = Year - (RHIWidth*0.07),
          y = `Ground Source heat pump`,
          label = ifelse(Year == min(Year), format(`Ground Source heat pump`, big.mark = ","), ""),
          hjust = 0.5,
          vjust = 1,
          fontface = 2
        ),colour = LineColours[4],
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = Year + (RHIWidth*0.07),
          y = `Ground Source heat pump`,
          label = ifelse(Year == max(Year), format(`Ground Source heat pump`, big.mark = ","), ""),
          hjust = 0.5,
          vjust = 0,
          fontface = 2
        ),colour = LineColours[4],
        family = "Century Gothic"
      ) +
      geom_point(
        data = tail(RHIDom, 1),
        aes(
          x = Year,
          y = `Ground Source heat pump`,
          show_guide = FALSE
        ),colour = LineColours[4],
        size = 4,
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = mean(Year)-3,
          y = mean(`Ground Source heat pump`,),
          label = "Ground Source heat pump",
          hjust = 0.5,
          vjust = 1.6,
          
          fontface = 2
        ),colour = LineColours[4],
        family = "Century Gothic"
      ) +
      geom_line(
        aes(
          y = `Biomass`,
          label = percent(`Biomass`)
        ),
        colour = LineColours[3],
        size = 1.5,
        family = "Century Gothic"
      )+ 
      geom_text(
        aes(
          x = Year - (RHIWidth*0.07),
          y = `Biomass`,
          label = ifelse(Year == min(Year), format(`Biomass`, big.mark = ","), ""),
          hjust = 0.5,
          vjust = 0,
          fontface = 2
        ),colour = LineColours[3],
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = Year + (RHIWidth*0.07),
          y = `Biomass`,
          label = ifelse(Year == max(Year), format(`Biomass`, big.mark = ","), ""),
          hjust = 0.5,
          
          fontface = 2
        ),colour = LineColours[3],
        family = "Century Gothic"
      ) +
      geom_point(
        data = tail(RHIDom, 1),
        aes(
          x = Year,
          y = `Biomass`,
          show_guide = FALSE
        ),colour = LineColours[3],
        size = 4,
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = mean(Year)-3,
          y = mean(`Biomass`,),
          label = "Biomass",
          hjust = 0.5,
          vjust = 1,
          
          fontface = 2
        ),colour = LineColours[3],
        family = "Century Gothic"
      ) +
      geom_line(
        aes(
          y = `Solar Thermal`,
          label = percent(`Solar Thermal`)
        ),
        colour = LineColours[5],
        size = 1.5,
        family = "Century Gothic"
      )+ 
      geom_text(
        aes(
          x = Year - (RHIWidth*0.07),
          y = `Solar Thermal`,
          label = ifelse(Year == min(Year), format(`Solar Thermal`, big.mark = ","), ""),
          hjust = 0.5,
          vjust = -0.1,
          fontface = 2
        ),colour = LineColours[5],
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = Year + (RHIWidth*0.07),
          y = `Solar Thermal`,
          label = ifelse(Year == max(Year), format(`Solar Thermal`, big.mark = ","), ""),
          hjust = 0.5,
          vjust = 1.1,
          fontface = 2
        ),colour = LineColours[5],
        family = "Century Gothic"
      ) +
      geom_point(
        data = tail(RHIDom, 1),
        aes(
          x = Year,
          y = `Solar Thermal`,
          show_guide = FALSE
        ),colour = LineColours[5],
        size = 4,
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = mean(Year)-3,
          y = mean(`Solar Thermal`),
          label = "Solar Thermal",
          hjust = 0.5,
          vjust = -1,
          
          fontface = 2
        ),colour = LineColours[5],
        family = "Century Gothic"
      ) +
      geom_line(
        aes(
          y = `Total`,
          label = percent(`Total`)
        ),
        colour = LineColours[1],
        size = 1.5,
        family = "Century Gothic"
      )+ 
      geom_text(
        aes(
          x = Year  - (RHIWidth*0.07),
          y = `Total`,
          label = ifelse(Year == min(Year), format(`Total`, big.mark = ","), ""),
          hjust = 0.5,
          fontface = 2
        ),colour = LineColours[1],
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = Year  + (RHIWidth*0.07),
          y = `Total`,
          label = ifelse(Year == max(Year), format(`Total`, big.mark = ","), ""),
          hjust = 0.5,
          
          fontface = 2
        ),colour = LineColours[1],
        family = "Century Gothic"
      ) +
      geom_point(
        data = tail(RHIDom, 1),
        aes(
          x = Year,
          y = `Total`,
          show_guide = FALSE
        ),colour = LineColours[1],
        size = 4,
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = mean(Year)-3,
          y = mean(`Total`),
          label = "Total",
          hjust = 0.5,
          vjust = 1,
          
          fontface = 2
        ),colour = LineColours[1],
        family = "Century Gothic"
      ) +
      geom_text(
        aes(
          x = Year,
          y = 0,
          label = ifelse(Year == max(Year) |
                           Year == min(Year), format(Year, format = "%b %Y"), ""),
          hjust = 0.5,
          vjust = 1.5,
          fontface = 2
        ),
        colour = LineColours[1],
        family = "Century Gothic"
      )+
      geom_hline(
        yintercept = 0,
        color = "grey",
        alpha = 0.7,
        linetype = 2
      )
    
    
    RHIDomChart <-
      DailyChart(RHIDomChart,
                 RHIDom,
                 plottitle,
                 sourcecaption,
                 ChartColours)
    
    RHIDomChart <- RHIDomChart+
      coord_cartesian(xlim = c(min(RHIDom$Year) - (RHIWidth*0.09), max(RHIDom$Year)+ (RHIWidth*0.09))) +
      ylim(-50,max(RHIDom$Total))
    
    
    RHIDomChart
    
    
    ggsave(
      file,
      plot = RHIDomChart,
      width = 15.5,
      height = 15,
      units = "cm",
      dpi = 300
    )
    
    
  }
)

output$DomRHIUrbanRuralSubtitle <- renderText({
  
  paste("Scotland,","April 2014 to December 2020")
})

output$DomRHIUrbanRuralPlot <- renderPlotly  ({
  
  DomUrbanRural <- read_delim("Processed Data/Output/RHI/DomUrbanRural.txt", 
                              "\t", escape_double = FALSE, trim_ws = TRUE)
  
  DomUrbanRural$OnGridProp <- DomUrbanRural$`Total on-grid` / DomUrbanRural$Total
  
  DomUrbanRural$OffGridProp <- DomUrbanRural$`Total off-grid` / DomUrbanRural$Total
  
  DomUrbanRural <- DomUrbanRural[c(1,11,12)]
  
  DomUrbanRural$Tech <- paste0("<b>", DomUrbanRural$Tech, "</b>")
  
  DomUrbanRural$Tech <- factor(DomUrbanRural$Tech, levels = c(as.character(DomUrbanRural$Tech)))
  
  ChartColours <- c("#004529", "#78c679")
  
  p <- plot_ly(
    data = DomUrbanRural,
    y = ~Tech,
    x = ~OnGridProp,
    text = paste0(DomUrbanRural$Tech,
                  "\nProportion of accreddited installations that are on-grid: ",
                  percent(DomUrbanRural$OnGridProp,.1), ""
    ),
    name = "On-grid",
    type = "bar",
    hoverinfo = "text",
    orientation = 'h',
    legendgroup = '1',
    marker = list(color =  ChartColours[1])
  )  %>% 
    add_trace(
      y = ~Tech,
      x = ~OffGridProp,
      text = paste0(DomUrbanRural$Tech,
                    "\nProportion of accreddited installations that are off-grid: ",
                    percent(DomUrbanRural$OffGridProp,.1), ""
      ),
      name = "Off-grid",
      type = "bar",
      hoverinfo = "text",
      orientation = 'h',
      legendgroup = '2',
      marker = list(color =  ChartColours[2])
    ) %>% 
    layout(
      barmode = 'stack',
      legend = list(font = list(color = "#39ab2c"),
                    orientation = 'h'),
      hoverlabel = list(font = list(color = "white"),
                        hovername = 'text'),
      hovername = 'text',
      yaxis = list(title = "",
                   autorange = "reversed",
                   showgrid = FALSE),
      xaxis = list(
        title = "",
        tickformat = "%",
        showgrid = TRUE,
        zeroline = TRUE,
        zerolinecolor = ChartColours[1],
        zerolinewidth = 2,
        rangemode = "tozero"
      )
    ) %>% 
    config(displayModeBar = F)
  
  p
  
  
  
  
})

output$DomRHIUrbanRural.png <- downloadHandler(
  filename = "DomRHIUrbanRural.png",
  content = function(file) {
    
    Data <- read_delim("Processed Data/Output/RHI/DomUrbanRural.txt", 
                       "\t", escape_double = FALSE, trim_ws = TRUE)
    
    Data$OffGridProp <- Data$`Total off-grid` / Data$Total
    Data$OnGridProp <- Data$`Total on-grid` / Data$Total
    
    Data <- Data[c(1,11,12)]
    
    ChartColours <- "#39ab2c"
    BarColours <- c("#004529", "#78c679")
    
    Data$Tech <-
      factor(Data$Tech,
             levels = rev(unique(Data$Tech)),
             ordered = TRUE)
    
    Data <- melt(Data, id.vars = "Tech")
    
    
    Data$variable <-
      factor(
        Data$variable,
        levels = unique(Data$variable),
        ordered = TRUE
      )
    
    Data <- Data %>%
      group_by(Tech) %>%
      mutate(pos = cumsum(value) - value / 2) %>%
      mutate(top = sum(value))
    
    
    ### variables
    sourcecaption = "Source: BEIS"
    plottitle = "Proportion of full accreditations which are on-grid and off-grid"
    
    DataChart <- Data %>%
      ggplot(aes(x = Tech, y = value, fill = variable, color = variable), family = "Century Gothic") +
      scale_fill_manual(
        "variable",
        values = c(
          "OnGridProp" = BarColours[1],
          "OffGridProp" = BarColours[2]
        )
      ) +
      scale_colour_manual(values=c(BarColours[2],BarColours[1] )) +
      geom_bar(position = "stack",
               stat = "identity",
               width = .8) +
      coord_flip() +
      geom_text(aes(
        y = (top - pos),
        label = percent(value, .1),
        
      ),
      fontface = 2,
      colour = "white",
      size = 3,
      family = "Century Gothic") +
      geom_text(
        y = -0.175,
        label = str_wrap(Data$Tech, 20),
        fontface = 2,
        family = "Century Gothic",
        vjust = .5,
        color = ChartColours[1]
      ) +
      geom_text(
        aes(x = 5.7,
            y = 0,
            label = "On-grid"),
        fontface = 2,
        colour = BarColours[1],
        family = "Century Gothic",
        hjust = 0
      ) +
      geom_text(
        aes(x = 5.7,
            y = 1,
            label = "Off-grid"),
        fontface = 2,
        colour = BarColours[2],
        family = "Century Gothic",
        hjust = 1
      ) +
      geom_text(
        aes(x = 6.2,
            y = 0.29,
            label = " "),
        fontface = 2,
        colour = ChartColours[1],
        family = "Century Gothic",
        hjust = 0.5
      ) +
      theme(
        text = element_text(family = "Century Gothic")
        ,
        panel.background = element_rect(fill = "transparent") # bg of the panel
        ,
        plot.background = element_rect(fill = "transparent", color = NA) # bg of the plot
        ,
        legend.background = element_rect(fill = "transparent") # get rid of legend bg
        ,
        legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
        ,
        legend.title = ggplot2::element_blank()
        ,
        axis.text.x = element_blank()
        ,
        axis.text.y = element_blank()
        ,
        axis.title = ggplot2::element_blank()
        ,
        legend.text = element_text(colour = "black", family = "Century Gothic")
        ,
        axis.ticks = ggplot2::element_blank()
        ,
        panel.grid.major = ggplot2::element_blank()
        ,
        legend.position = "none"
        ,
        title = element_text(colour = ChartColours[1], size = 14)
        ,
        plot.title = ggplot2::element_text(face = "bold")
      ) + ### Label Plot
      labs(y = "Percentage", caption = sourcecaption) +
      labs(title = plottitle,
           face = "bold",
           subtitle = "Scotland, April - June 2020") +
      ### 0 Axis
      
      #geom_hline(yintercept=.52, color = ChartColours[2], alpha = 0.7)+
      
      
      ### Plot Borders
      annotate(
        geom = 'segment',
        x = Inf,
        xend = Inf,
        color = ChartColours[1],
        y = -Inf,
        yend = Inf,
        size = 1.5
      ) +
      annotate(
        geom = 'segment',
        x = -Inf,
        xend = -Inf,
        color = ChartColours[1],
        y = -Inf,
        yend = Inf,
        size = 1
      ) +
      ylim(-.3,1)
    
    DataChart
    
    DataChart <-
      DataChart +
      labs(subtitle = paste("Scotland, April 2014 to December 2020")) 
    
    DataChart
    
    ggsave(
      file,
      plot = DataChart,
      width = 22,
      height = 14,
      units = "cm",
      dpi = 300
    )
    
    
    
  }
)

}
    
    